<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SmartDocHub.Service</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartDocHub.Domain\SmartDocHub.Domain.csproj" />
    <ProjectReference Include="..\SmartDocHub.Infrastructure\SmartDocHub.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="PermissionApp\Dto\" />
  </ItemGroup>

</Project>
